# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing_extensions import Literal, TypeAlias

__all__ = ["SupportedModel"]

SupportedModel: TypeAlias = Literal[
    "SUPPORTED_MODEL_UNSPECIFIED",
    "SUPPORTED_MODEL_SONNET_3_5",
    "SUPPORTED_MODEL_SONNET_3_7",
    "SUPPORTED_MODEL_SONNET_3_7_EXTENDED",
    "SUPPORTED_MODEL_SONNET_4",
    "SUPPORTED_MODEL_SONNET_4_EXTENDED",
    "SUPPORTED_MODEL_SONNET_4_5",
    "SUPPORTED_MODEL_SONNET_4_5_EXTENDED",
    "SUPPORTED_MODEL_SONNET_4_6",
    "SUPPORTED_MODEL_SONNET_4_6_EXTENDED",
    "SUPPORTED_MODEL_SONNET_5",
    "SUPPORTED_MODEL_OPUS_4",
    "SUPPORTED_MODEL_OPUS_4_EXTENDED",
    "SUPPORTED_MODEL_OPUS_4_5",
    "SUPPORTED_MODEL_OPUS_4_5_EXTENDED",
    "SUPPORTED_MODEL_OPUS_4_6",
    "SUPPORTED_MODEL_OPUS_4_6_EXTENDED",
    "SUPPORTED_MODEL_OPUS_4_7",
    "SUPPORTED_MODEL_OPUS_4_8",
    "SUPPORTED_MODEL_HAIKU_4_5",
    "SUPPORTED_MODEL_OPENAI_4O",
    "SUPPORTED_MODEL_OPENAI_4O_MINI",
    "SUPPORTED_MODEL_OPENAI_O1",
    "SUPPORTED_MODEL_OPENAI_O1_MINI",
    "SUPPORTED_MODEL_OPENAI_AUTO",
]
